version: "3.7"

services:
  ghost:
    image: ghost:5-alpine
    platform: linux/amd64
    container_name: ghost
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 2368:2368
    volumes:
      - ./.docker/ghost:/var/lib/ghost/content
      - ./themes:/var/lib/ghost/content/themes